### ISSUE TITLE
Tip: Light/Dark Custom Icons

### ISSUE THREAD

**Issue by lainsce** [Blquinn/notes#12]
If you install via meson your custom icons to `/usr/share/icons/hicolor/scalable/apps`, they should recolor automatically.

Here's a meson snippet:

```python
icondir = join_paths(get_option('datadir'), 'icons/hicolor')

install_data(
  '@0@.svg'.format(app_id),
  install_dir: join_paths(icondir, 'scalable/apps'),
)
```

**Comment by blquinn** [comment]
It's like you're in the room with me... I was just trying to figure out how to do this lol.

Thanks, I will give that a shot!

**Comment by blquinn** [comment]
That worked :) Thanks!
