### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by SilverMarcs** [Blquinn/notes#13]
The padding here seems a bit off. I am talking about the space (or lack thereof) between notebook title and note card. Probably aware of this already but putting it here anyway to document this

![image](https://user-images.githubusercontent.com/77480421/163943399-52e84a88-1ac8-4b9a-a30a-5f4fc7c99323.png)

**Comment by blquinn** [comment]
Yea I think the header section just needs a little padding on the bottom.
