### ISSUE TITLE
Hard-coded directory string in me.blq.notes.json

### ISSUE THREAD

**Issue by baumkuchen42** [Blquinn/notes#16]
**Issue:** Flatpak build fails/needs manual intervention because source URL is hard-coded in me.blq.notes.json
**Error Message:** 
```bash
fatal: '/home/ben/Code/gnome/notes' does not appear to be a git repository
fatal: Could not read from remote repository.
```
**Temporary solution:** Change the directory path in modules.sources.url in the JSON file to location of source code on own machine

To make the flatpak build described in the [README](https://github.com/Blquinn/notes#flatpak) work, it would be great if you change this!

**Comment by blquinn** [comment]
Oops 😵‍💫 I don't have my Linux computer with me this weekend, but can fix this next week.

**Comment by blquinn** [comment]
This now references the git repo
