### ISSUE TITLE
Don't use your application's constructor for initialization operations.

### ISSUE THREAD

**Issue by nyx-lyb3ra** [Blquinn/notes#3]
It will cause this code to run EVERY TIME a new non-primary instance is launched, unnecessarily since it will immediately close and send an `activate` event to the primary instance. Override the virtual `startup` method instead, which is guaranteed to run only once in the entire lifecycle of your app (just don't forget to chain up at the beginning, weird things may happen otherwise)

See https://developer.gnome.org/documentation/tutorials/application.html

https://github.com/Blquinn/notes/blob/c3e78b1855c88070d8963a823909e3afb2264274/src/application.vala#L33-L37

**Comment by blquinn** [comment]
Are you sure the constructor can run multiple times? I'm not sure how that would be possible since that would require deleting then re-creating the application instance. I think that only the activate signal can run multiple times.

**Comment by nyx-lyb3ra** [comment]
> Are you sure the constructor can run multiple times?

When your application command is executed, the first thing that happens is that the `main()` function is called, which creates an object of the `NotesApplication` class, executing its constructor. Then the `run()` method is called, which actually checks if the app is the only instance running, and if it is not, it forwards all the necessary info to the main instance, and then immediately closes itself.
