### ISSUE TITLE
Why don't you use GtkBuilder?

### ISSUE THREAD

**Issue by nyx-lyb3ra** [Blquinn/notes#4]
I noticed that you build the application interface completely by hand, instead of simply describing it in an XML document and linking it to your code via `[GtkTemplate]`… is there a reason behind this?

**Comment by blquinn** [comment]
I originally started out with UI files, however I faced some issues with libadwaita where certain attributes weren't named correctly and it blocked me from using them.

Overall, I'm not sure how much I like the xml that gtk provides anyway, it's extremely verbose compared to other markup languages, plus there's no good code completion, or anything for it. Vala's builder syntax is actually kind of nice and it works with autocomplete etc in the editor.

**Comment by nyx-lyb3ra** [comment]
It is true that XML is quite verbose, which is why Blueprint was born. If you want to keep using pure code, fine, that's what elementary does. I was just curious.

When you are going to use `GtkListView`, you can then use `GtkSignalListItemFactory` for the items :)

**Comment by blquinn** [comment]
Yea I've heard of blueprint. I actually quite liked it, but it seems pretty early in development. There were a couple things I couldn't do with it's syntax when I tried it a few months ago. I will probably give it another shot in another few months.
