### ISSUE TITLE
[Feature Request] Clipboard image pasting

### ISSUE THREAD

**Issue by SilverMarcs** [Blquinn/notes#7]
Would it be possible to paste images from clipboard onto the clipboard canvas? That would be an extremely handy tool to enhance the note taking expereience.

**Comment by blquinn** [comment]
Pasting in images is already supported. Give it a shot and let me know if you have any issues. Otherwise I'll close this out.

**Comment by SilverMarcs** [comment]
I'd have to install linux to try it out myself but if you say pasting images from clipboard is already supported, feel free to close the issue.

**Comment by blquinn** [comment]
Okay, closing.
