### ISSUE TITLE
Issues regarding libadwaita dark theme

### ISSUE THREAD

**Issue by nasfrost** [Blquinn/notes#8]
When using the libadwaita dark theme enabled through the Appearance menu in GNOME 42's Settings app, the input field for the body of the note remains white. This is the only case of this: the title and search input fields display as expected. Moreover, the numbered list, code block and quote block buttons remain dark coloured when using this theme, whereas the other icons adapt accordingly.
![image](https://user-images.githubusercontent.com/72759899/163705327-fd183306-229b-460a-9ee7-ae40ed559c5f.png)

**Comment by blquinn** [comment]
Thanks for the feedback. I am aware of this issue. 

I need to update the editor's css dynamically based on the active theme. It shouldn't be too hard, but I would like to think of a clean way of doing it.

Going to leave this open to track the issue.

**Comment by blquinn** [comment]
Editor fixed in https://github.com/Blquinn/notes/commit/48f5a0598e3ba47847fcecd5505573c266f311b7

Still need to address those icons.
